### ISSUE TITLE
Date slip with getNext()

### ISSUE THREAD

**Issue by ThomasPerraudin** [poliander/cron#9] opened 2022-03-25 09:03 UTC
```
$c = new \Cron('0 3 * * *');
echo $c->getNext();
```
___
### When run at 2022-03-25 01:55:01
Expected:

2022-03-25 03:00:00
...

Actual:

2022-03-25 03:00:00 **OK**
...
___
### When run at 2022-03-25 02:00:01
Expected:

2022-03-25 03:00:00
...

Actual:

2022-03-**26** 03:00:00 **ERROR**
...

**Comment by poliander** [comment] 2022-03-25 09:47
Did you consider the timezone correctly? If you specify a starting timestamp (GMT) for 02:00:01 and set the timezone e.g. for Paris (European Central Time = GMT+1:00) then this behaviour would actually be correct, since your actual starting time would be 03:00:01.

You could try to pseudo-disable timezone to verify:
$which = new CronExpression($expression, new DateTimeZone('GMT'));

**Comment by poliander** [comment] 2022-03-25 10:32
@ThomasPerraudin 

Can you please check wether your timezone setting is correct?

`$ php -i | grep timezone
Default timezone => Europe/Berlin`

**Comment by ThomasPerraudin** [comment] 2022-03-25 10:56
Thank you for you quick answer.


`$ php -i | grep timezone
Default timezone => Europe/Berlin
date.timezone => no value => no value
`

Thomas Perraudin
Dirigeant Fondateur

***@***.***
+33 (0)6 81 60 32 16 <tel:+33681603216>

Cerebellis <https://www.cerebellis.com> 	
Conseil et développement logiciel
Spécialistes des sciences de la vie

LinkedIn <https://linkedin.com/company/cerebellis> 	Twitter 
<https://twitter.com/Cerebellis_fr> 	Facebook 
<https://facebook.com/cerebellis>

www.cerebellis.com <https://www.cerebellis.com>



Le 25/03/2022 à 11:33, René Pollesch a écrit :

**Comment by poliander** [comment] 2022-03-25 10:58
@ThomasPerraudin

I can confirm that the current behaviour is not as it should be.

**Comment by poliander** [comment] 2022-03-25 11:00
Fixed in v2.4.1

**Closed** 2022-03-25 10:59 UTC
Labels: bug

**Comment by ThomasPerraudin** [comment] 2022-03-25 11:03
@poliander Thank you.
